### ISSUE TITLE
No enum constant org.bukkit.Material.EXPERIENCE_BOTTLE

### ISSUE THREAD

**Issue by PilgrimViis** [Falseee/Builder-s-Wand#25]
Hi. I cannot add experience bottle in recipe to craft builder's wand. Here is my config
```
wands:
  '1':
    name: '&3Builders grimoire'
    material: BOOK
    maxSize: 8
    consumeItems: true
    durability:
      amount: 130
      enabled: true
      text: '&5Durability: &e{durability}'
    crafting:
      ingredient:
        a: REDSTONE
        b: EXPERIENCE_BOTTLE
        c: OBSIDIAN
        d: BOOK
        e: NETHER_STAR
      enabled: true
      shapeless: false
      recipe:
      - aba
      - cdc
      - ece
    particles:
      enabled: true
      type: REDSTONE
      count: 3
    storage:
      enabled: true
      size: 27
```

And it is exception I'm getting.

````
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BuildersWand v2.3.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.EXPERIENCE_BOTTLE
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_171]
	at org.bukkit.Material.valueOf(Material.java:1) ~[spigot2.jar:git-Spigot-642f6d2-6103339]
	at de.False.BuildersWand.manager.WandManager.getIngredientList(WandManager.java:147) ~[?:?]
	at de.False.BuildersWand.manager.WandManager.getWand(WandManager.java:59) ~[?:?]
	at de.False.BuildersWand.manager.WandManager.getWandTier(WandManager.java:183) ~[?:?]
	at de.False.BuildersWand.Commands.giveCommand(Commands.java:102) ~[?:?]
	at de.False.BuildersWand.Commands.onCommand(Commands.java:52) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot2.jar:git-Spigot-642f6d2-6103339]
````

But in spigot docs I'm clearly see this constant. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html#EXPERIENCE_BOTTLE

**Comment by Falseee** [comment]
I think EXPERIENCE_BOTTLE is new in the 1.13 as particle, the plugins currently only work with 1.12 particles.

**Comment by Falseee** [comment]
@PilgrimViis 
Works with a 1.13 server ?

**Comment by PilgrimViis** [comment]
@Falseee thanks for answering. I'm on 1.12.2 currently, so it's not suppose to work with this version. I'll try again at 1.13 =)
