### ISSUE TITLE
Plugin does not enable on minecraft version 1.19.3

### ISSUE THREAD

**Issue by RhythmicSys** [Falseee/Builder-s-Wand#80]
Attempting to use builders wand plugin on version `1.19.3` results in this:
```
[04:09:11 ERROR]: Error occurred while enabling BuildersWand v2.27.0 (Is it up to date?)
java.lang.RuntimeException: Could not found nms for version v1_19_R2
        at de.False.BuildersWand.Main.setupNMS(Main.java:150) ~[Builders_Wand-2.27.0.jar:?]
        at de.False.BuildersWand.Main.onEnable(Main.java:39) ~[Builders_Wand-2.27.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1860]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1860]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.3.jar:git-Purpur-1860]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.19.3.jar:git-Purpur-1860]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:336) ~[purpur-1.19.3.jar:git-Purpur-1860]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1115) ~[purpur-1.19.3.jar:git-Purpur-1860]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[purpur-1.19.3.jar:git-Purpur-1860]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Here is the full log if it helps:
https://mclo.gs/yiOUl8I#L313

I realize the free version is no longer supported- however since the premium version has not gotten an update since 1.19.3 was released either, I would guess the problem is the same there

**Comment by UtechtDustin** [comment]
Updated to 1.19.3, thanks for the hint.
